name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: ERP Client pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 14.15.0
            NODE_OPTIONS: "--max-old-space-size=8192"
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.15.0

            - name: Install node.js packages
              run: npm install

            # - name: Run frontend test
            #  run: npm run test

            - name: Package application
              run: npm run webapp:build:prod

            - name: Login to Docker hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build docker image
              run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_ORG }}/${{ secrets.DOCKERHUB_REPO }}:1.7.8

            - name: Push docker image
              run: docker push ${{ secrets.DOCKERHUB_ORG }}/${{ secrets.DOCKERHUB_REPO }}:1.7.8
