# ===================================================================
# File Uploads Streams and Batch configurations
#
# This configuration overrides the application.yml file.
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# Configure list-page sizes
reader:
  listSize: ${UPLOADS_SIZE}
spring:
  batch:
    job:
      enabled: false
