export enum AccountSubTypes {
  SETTLEMENT_ASSET = 'SETTLEMENT_ASSET',

  ACCOUNT_RECEIVABLE = 'ACCOUNT_RECEIVABLE',

  OTHER_SHORT_LIVED_ASSET = 'OTHER_SHORT_LIVED_ASSET',

  LONG_LIVED_ASSET = 'LONG_LIVED_ASSET',

  ACCOUNT_PAYABLE = 'ACCOUNT_PAYABLE',

  OTHER_SHORT_LIVED_LIABILITY = 'OTHER_SHORT_LIVED_LIABILITY',

  LONG_LIVED_LIABILITY = 'LONG_LIVED_LIABILITY',

  INCOME = 'INCOME',

  EXPENSE = 'EXPENSE',

  OTHER_COMPREHENSIVE_INCOME = 'OTHER_COMPREHENSIVE_INCOME',
}
