export enum CategoryTypes {
  UNDEFINED = 'UNDEFINED',

  CATEGORY0 = 'CATEGORY0',

  CATEGORY1 = 'CATEGORY1',

  CATEGORY2 = 'CATEGORY2',

  CATEGORY3 = 'CATEGORY3',

  CATEGORY4 = 'CATEGORY4',

  CATEGORY5 = 'CATEGORY5',

  CATEGORY6 = 'CATEGORY6',

  CATEGORY7 = 'CATEGORY7',

  CATEGORY8 = 'CATEGORY8',

  CATEGORY9 = 'CATEGORY9',

  CATEGORY10 = 'CATEGORY10',

  CATEGORY11 = 'CATEGORY11',

  CATEGORY12 = 'CATEGORY12',

  CATEGORY13 = 'CATEGORY13',

  CATEGORY14 = 'CATEGORY14',

  CATEGORY15 = 'CATEGORY15',

  CATEGORY16 = 'CATEGORY16',

  CATEGORY17 = 'CATEGORY17',
}
