export enum FileModelType {
  CURRENCY_LIST = 'CURRENCY_LIST',

  FIXED_ASSET_ACQUISITION = 'FIXED_ASSET_ACQUISITION',

  FIXED_ASSET_DEPRECIATION = 'FIXED_ASSET_DEPRECIATION',

  FIXED_ASSET_NBV = 'FIXED_ASSET_NBV',

  PAYMENT_LABEL = 'PAYMENT_LABEL',

  PAYMENT_CATEGORY = 'PAYMENT_CATEGORY',

  PAYMENT = 'PAYMENT',

  DEALER = 'DEALER',

  SIGNED_PAYMENT = 'SIGNED_PAYMENT',

  INVOICE = 'INVOICE',
}
