export enum taxReferenceTypes {
  TELCO_EXCISE_DUTY = 'TELCO_EXCISE_DUTY',

  VALUE_ADDED_TAX = 'VALUE_ADDED_TAX',

  WITHHOLDING_VAT = 'WITHHOLDING_VAT',

  WITHHOLDING_TAX_ON_CONSULTANCY = 'WITHHOLDING_TAX_ON_CONSULTANCY',

  WITHHOLDING_TAX_ON_RENT = 'WITHHOLDING_TAX_ON_RENT',

  CATERING_LEVY = 'CATERING_LEVY',

  SERVICE_CHARGE = 'SERVICE_CHARGE',

  WITHHOLDING_TAX_ON_IMPORTED_SERVICE = 'WITHHOLDING_TAX_ON_IMPORTED_SERVICE',
}
