#
# Erp System - Mark X No 11 (Jehoiada Series) Client 1.7.9
# Copyright © 2021 - 2024 Edwin Njeru (mailnjeru@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

FROM node:14.21.3-alpine AS build

WORKDIR /opt/app

COPY package.json package-lock.json ./
RUN npm install --silent

COPY . .

ENV PATH="./node_modules/.bin:$PATH" \
    NODE_OPTIONS="--max-old-space-size=4096"

RUN npm run webapp:build:dev

FROM nginx:1.23.1-alpine

COPY src/main/docker/nginx/default.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /opt/app/target/classes/static /usr/share/nginx/html
COPY src/main/docker/docker-defaults.sh /
RUN chmod +x /docker-defaults.sh

ENTRYPOINT ["/docker-defaults.sh"]
CMD ["nginx", "-g", "daemon off;"]
