#
# Erp System - Mark X No 10 (Jehoiada Series) Server ver 1.8.2
# Copyright © 2021 - 2024 Edwin Njeru and the ERP System Contributors (mailnjeru@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
#version: '3.8'
version: '3.3'
services:
  erpsystem-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    # volumes:
    #   - ~/volumes/jhipster/erpSystem/elasticsearch/:/usr/share/elasticsearch/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      #- 127.0.0.1:9200:9200
      #- 9200:9200
      #- 127.0.0.1:9300:9300
      #- 9300:9300
      - 9301:9301
      - 9201:9201
    environment:
      - 'xpack.security.enabled=false'
      - 'discovery.type=single-node'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    cap_add:
#      - IPC_LOCK
