export const enum FileModelType {
  CURRENCY_LIST = 'CURRENCY_LIST',

  FIXED_ASSET_ACQUISITION = 'FIXED_ASSET_ACQUISITION',

  FIXED_ASSET_DEPRECIATION = 'FIXED_ASSET_DEPRECIATION',

  FIXED_ASSET_NBV = 'FIXED_ASSET_NBV',
}
